services:
  pkmovie-app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - pkmovie-db
  pkmovie-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pkmovie
    ports:
      - "5433:5432"
    volumes:
      - pkmovie_db_data:/var/lib/postgresql/data
volumes:
  pkmovie_db_data:
