name: Pk Movie Build

on:
  push:
    branches: [main]

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Create env file for Docker
        run: |
          echo "${{ secrets.DOTENV_FILE }}" > .env.docker

      - name: Build and push Docker image
        run: |
          docker compose build 
          docker compose push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets (Check if empty)
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then echo "HOST IS EMPTY"; else echo "HOST IS SET"; fi
          if [ -z "${{ secrets.SERVER_USER }}" ]; then echo "USER IS EMPTY"; else echo "USER IS SET"; fi